### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MrAn0nym** [Nyveon/MCStructureCleaner#5]
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/[…]/main.py", line 65, in _remove_tags_region
  File "/[…]/main.py", line 92, in remove_tags_region
  File "/usr/local/lib/python3.9/dist-packages/anvil/region.py", line 52, in chunk_location
    sectors = self.data[b_off + 3]
IndexError: index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/[…]/main.py", line 230, in <module>
  File "/[…]/main.py", line 219, in _main
  File "/[…]/main.py", line 132, in remove_tags
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: index out of range
```

Occurred on pop os 21.04, python3.9

**Comment by Nyveon** [comment]
Hi! That's a bit strange... would love to fix this but I'm not sure what could be causing it.
Do you think you could send me the input you're using? (Command line arguments and the world folder, if it is too big, maybe a sample)
Otherwise we could get in contact perhaps? My discord is Nyveon#9999

**Comment by MrAn0nym** [comment]
When searching through the region files it turned out that the crash was caused by a few glitched 0 byte files. Thanks nonetheless ^^
